# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Java-Mx.BitChat
PackageVersion: 0.1.0
InstallerLocale: en-US
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Commands:
- bitchat
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Java-Mx/bitchat-python/releases/download/v0.1.0/BitChat-0.1.0-windows-x64.exe
  InstallerSha256: A8967BAE048E1C982FAD5FFBC9C657FB86CC8806E34A07C7564D3259F5B81C0A
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2026-09-29
